# Generated by Django 5.2 on 2025-05-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobpost_experience_level_savedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('rejected', 'Rejected'), ('hired', 'Hired'), ('pending', 'Pending')], default='applied', max_length=20),
        ),
    ]
