# Generated by Django 5.2 on 2025-06-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_directapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='agreement_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
