# Generated by Django 5.2 on 2025-06-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_bid_agreement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='agreement_pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
