# Generated by Django 5.2 on 2025-06-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_bid_agreement_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='bid_budget',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='bid_candidates',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
