# Generated by Django 5.2 on 2025-06-10 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_candidatesubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatesubmission',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='candidatesubmission',
            name='status',
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='jobs.candidatesubmission')),
            ],
        ),
    ]
