# Generated by Django 5.2 on 2025-06-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_candidatesubmission_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('assessment', 'Assessment'), ('phone_screen', 'Phone Screen'), ('interview', 'Interview Scheduled'), ('technical_interview', 'Technical Interview'), ('hr_interview', 'HR Interview'), ('reference_check', 'Reference Check'), ('background_check', 'Background Check'), ('offer_pending', 'Offer Pending'), ('offer_extended', 'Offer Extended'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('onboarding', 'Onboarding'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('on_hold', 'On Hold')], default='pending', max_length=20),
        ),
    ]
