# Generated by Django 5.2 on 2025-06-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_resume_name_alter_resume_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if status is rejected', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('assessment', 'Assessment'), ('phone_screen', 'Phone Screen'), ('interview', 'Interview Scheduled'), ('technical_interview', 'Technical Interview'), ('l1_interview', 'L1 Interview'), ('l2_interview', 'L2 Interview'), ('l3_interview', 'L3 Interview'), ('hr_interview', 'HR Interview'), ('reference_check', 'Reference Check'), ('background_check', 'Background Check'), ('offer_pending', 'Offer Pending'), ('offer_extended', 'Offer Extended'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('onboarding', 'Onboarding'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('on_hold', 'On Hold')], default='pending', max_length=20),
        ),
    ]
