# Generated by Django 5.2 on 2025-05-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_candidateprofile_about_candidateprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_culture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='core_business',
            field=models.TextField(blank=True, null=True),
        ),
    ]
