# Generated by Django 5.2 on 2025-05-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employerprofile_company_culture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancyprofile',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
