# Generated by Django 5.2 on 2025-05-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_consultancyprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='application_status',
            field=models.CharField(blank=True, default='pending', max_length=255, null=True),
        ),
    ]
