# Generated by Django 5.2 on 2025-05-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employerprofile_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='gstin_certificate',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='msme_or_incorporation_certificate',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='pan_card',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='poc_document',
            field=models.URLField(blank=True, null=True),
        ),
    ]
