# Generated by Django 5.2 on 2025-06-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_candidateprofile_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancyprofile',
            name='application_status',
            field=models.CharField(blank=True, choices=[('verifying', 'Verifying'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='verifying', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='application_status',
            field=models.CharField(blank=True, choices=[('verifying', 'Verifying'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='verifying', max_length=255, null=True),
        ),
    ]
