# Generated by Django 5.2 on 2025-05-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_employerprofile_gstin_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='resume',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultancyprofile',
            name='gstin_certificate',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultancyprofile',
            name='msme_or_incorporation_certificate',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultancyprofile',
            name='pan_card',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultancyprofile',
            name='poc_document',
            field=models.URLField(blank=True, null=True),
        ),
    ]
