# Generated by Django 5.2 on 2025-05-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_candidateprofile_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='resume_url',
        ),
    ]
