# Generated by Django 5.2 on 2025-05-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_candidateprofile_resume_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='preferenced_city',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='consultancyprofile',
            name='consultancy_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
