# Generated by Django 5.2 on 2025-05-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_candidateprofile_city_candidateprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='application_status',
            field=models.CharField(blank=True, default='verifying', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consultancyprofile',
            name='application_status',
            field=models.CharField(blank=True, default='verifying', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='application_status',
            field=models.CharField(blank=True, default='verifying', max_length=255, null=True),
        ),
    ]
