# Generated by Django 5.2 on 2025-05-07 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_education_user_alter_experience_user'),
        ('accounts', '0014_auto_add_timestamps'),
    ]

    operations = [
    ]
