# Generated by Django 5.2 on 2025-05-07 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_merge_20250507_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='education_type',
            field=models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('higher_secondary', 'Higher Secondary'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL),
        ),
    ]
