# Generated by Django 5.2 on 2025-05-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_education_education_type_alter_education_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_steps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='application_status',
            field=models.CharField(blank=True, default='approved', max_length=255, null=True),
        ),
    ]
