# Generated by Django 5.2 on 2025-05-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_completed_steps_user_registration_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_step',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
