# Generated by Django 5.2 on 2025-06-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_usersubscription_bid_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='bid_limit',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='job_limit',
            field=models.BigIntegerField(default=0),
        ),
    ]
